name: Orange-Fox
on:
  schedule:
    - cron:  '0 12 * * 6'

env:
  MANIFEST: https://gitlab.com/OrangeFox/Manifest.git -b fox_9.0
  DEVICE: markw
  DT_LINK: https://github.com/Tostisto/device_xiaomi_markw_twrp.git
  DT_PATH: device/xiaomi/markw


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Initializing environment
         run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
            sudo -E apt-get clean 
            sudo -E apt-get autoremove
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery source and device tree
         run: |
             mkdir recovery
             cd recovery
             repo init -u $MANIFEST --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -j4
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH

       - name: Build
         run: |
              cd recovery
              . build/envsetup.sh
              lunch omni_$DEVICE-eng
              export ALLOW_MISSING_DEPENDENCIES=true
              make recoveryimage
             
       - name: Releasing
         uses: "marvinpinto/action-automatic-releases@latest"
         with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "OrangeFox recovery"
          prerelease: false
          files: |
              recovery/out/target/product/*/*.zip
              recovery/out/target/product/*/recovery.img